spring:
  application:
    name: hello-service
server:
  port: 8095

eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true